### PR TITLE
fix: make HMR working again with latest vite version

### LINKED ISSUE #971: CORS policy blocks script access in development
### Build tool

Vite

### Where do you see the problem?

- [x] In the browser
- [ ] In the terminal

### Describe the bug

i create a react crx demo according to this guide [Get Started with React](https://crxjs.dev/vite-plugin/getting-started/react/create-project), when i run `pnpm dev`, i found this error info in chrome extension inspect page(chrome://extensions/?errors=gbfkgllkhphjnpfpgfgmpahkbekgeenh)

Image

the service-worker-loader.js's content is
```js
import 'http://localhost:5173/@vite/env';
import 'http://localhost:5173/@crx/client-worker';
```

my chrome version is  131.0.6778.265 (arm64)

### Reproduction

do according to [Get Started with React](https://crxjs.dev/vite-plugin/getting-started/react/create-project).

### Logs

```shell
Access to script at 'http://localhost:5173/@crx/client-worker' from origin 'chrome-extension://gbfkgllkhphjnpfpgfgmpahkbekgeenh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

### System Info

```shell
System:
    OS: macOS 12.7.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 121.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  npmPackages:
    @crxjs/vite-plugin: 2.0.0-beta.30 => 2.0.0-beta.30 
    @eslint/js: ^9.17.0 => 9.18.0 
    @types/react: ^18.3.18 => 18.3.18 
    @types/react-dom: ^18.3.5 => 18.3.5 
    @vitejs/plugin-react: ^4.3.4 => 4.3.4 
    eslint: ^9.17.0 => 9.18.0 
    eslint-plugin-react-hooks: ^5.0.0 => 5.1.0 
    eslint-plugin-react-refresh: ^0.4.16 => 0.4.18 
    globals: ^15.14.0 => 15.14.0 
    react: ^18.3.1 => 18.3.1 
    react-dom: ^18.3.1 => 18.3.1 
    typescript: ~5.6.2 => 5.6.3 
    typescript-eslint: ^8.18.2 => 8.20.0 
    vite: ^6.0.5 => 6.0.9
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by elwin013**
Fixing HMR with latest version of the Vite (`>=6.0.9`, `>=5.4.12, <6.0.0`, `>=4.5.6, <5.0.0`) - passing web socket token.

Changes based on comment from vite dev (https://github.com/crxjs/chrome-extension-tools/issues/971#issuecomment-2608871639) -  passing `config.webSocketToken` to `hmr-client-worker.ts` under the key `__HMR_TOKEN__`.

Closes #971

### CODE REVIEW

**Comment by elwin013** [comment]
In https://github.com/crxjs/chrome-extension-tools/pull/999/commits/d6fc56ce468b8b593b66e6d146b38bc1aabd9aa1 the image is removed from Svelte tests (as well as the check for the image). 

It changes the test, but makes it more stable. `await app.locator('img').evaluate(image => image.complete);` works randomly and adding artificial delay doesn't seem right.

File: packages/vite-plugin/src/node/defineClientValues.ts [hunk 1]
```diff
@@ -30,6 +30,8 @@ export function defineClientValues(code: string, config: ResolvedConfig) {
     .replace(`__MODE__`, JSON.stringify(config.mode))
     .replace(`__BASE__`, JSON.stringify(config.base))
     .replace(`__DEFINES__`, serializeDefine(config.define || {}))
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    .replace(`__HMR_TOKEN__`, JSON.stringify((config as any).webSocketToken))
```
Comment (AllenBW) [inline packages/vite-plugin/src/node/defineClientValues.ts:34]: Opposed to making a minimal interface? 

something like

```
interface ViteConfigWithHMR extends ResolvedConfig {
  webSocketToken?: string;
}
```

which would be used like this `.replace(`__HMR_TOKEN__`, JSON.stringify((config as ViteConfigWithHMR).webSocketToken || ''))
`

**Review by AllenBW — APPROVED** [review]
Thanks for this PR! This looks like a solid fix for HMR compatibility with newer Vite versions. The issue was that Vite now requires a WebSocket token to be passed for security, which this implementation properly handles.

File: packages/vite-plugin/src/node/defineClientValues.ts (hunk 1 above)
Comment (elwin013) [reply packages/vite-plugin/src/node/defineClientValues.ts]: Yes. But the minimal interface extending `ResolvedConfig` seems okay too - changed in https://github.com/crxjs/chrome-extension-tools/pull/999/commits/b93dcd173e825b6116830a1e688f59fbf6dfac19

**Comment by elwin013** [comment]
Rebased over the latest `main`.

**Review by Toumash — APPROVED** [review]
